### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Sciss** [aconley/Algorithms#2]
hi there - can you please specify the license of your project? I would be interested in using your MST implementation. thanks!

**Comment by aconley** [comment]
Added an MIT license.

This isn't a serious library -- if you are looking for scala
graph algorithms, you should probably consider something like
http://www.scala-graph.org/

**Comment by Sciss** [comment]
Thanks - I was just trying to find a MST implementation that I could use right away :) Anyway, got one working now.
